In [3]:
import numpy as np

# Creating a 1D array with numbers from 0 to 9
arr1 = np.arange(10)
print(arr1)


[0 1 2 3 4 5 6 7 8 9]


In [4]:
# Creating a 2D array (3x3) filled with ones
arr2 = np.ones((3, 3))
print(arr2)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# Creating a 3x3 identity matrix
arr3 = np.eye(3)
print(arr3)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# Creating an array with 20 evenly spaced numbers between 0 and 100
arr4 = np.linspace(0, 100, 20)
print(arr4)


[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]


In [7]:
# Slice the first three elements from arr1
sliced_array = arr1[:3]
print(sliced_array)


[0 1 2]


In [8]:
# Reshaping the 1D array into a 2D array of shape (2, 5)
reshaped_array = arr1.reshape(2, 5)
print(reshaped_array)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
# Finding sum, mean, and standard deviation of arr1
sum_value = np.sum(arr1)
mean_value = np.mean(arr1)
std_dev_value = np.std(arr1)

print("Sum:", sum_value)
print("Mean:", mean_value)
print("Standard Deviation:", std_dev_value)


Sum: 45
Mean: 4.5
Standard Deviation: 2.8722813232690143


In [10]:
import numpy as np

# Creating the 2D array with stock price data for 5 companies over 7 days
stock_data = np.array([
    [150, 152, 155, 158, 160, 162, 165],  # Company A
    [210, 215, 220, 225, 230, 235, 240],  # Company B
    [130, 132, 135, 137, 140, 145, 148],  # Company C
    [300, 305, 310, 315, 320, 325, 330],  # Company D
    [50, 52, 54, 55, 56, 58, 60]          # Company E
])

# Step 1: Reshape the data if necessary
# The data is already in a 2D format of shape (5, 7), so no reshaping is needed in this case.
print("Stock Data:\n", stock_data)

# Step 2: Calculate the mean stock price for each company (mean of each row)
mean_stock_prices = np.mean(stock_data, axis=1)
print("\nMean stock price for each company:", mean_stock_prices)

# Step 3: Find the company with the highest average stock price
company_with_highest_avg_price = np.argmax(mean_stock_prices)
companies = ["Company A", "Company B", "Company C", "Company D", "Company E"]
print("\nCompany with the highest average stock price:", companies[company_with_highest_avg_price])

# Step 4: Calculate the highest and lowest stock prices for each company across all days
highest_prices = np.max(stock_data, axis=1)
lowest_prices = np.min(stock_data, axis=1)
print("\nHighest stock price for each company:", highest_prices)
print("Lowest stock price for each company:", lowest_prices)

# Step 5: Identify the day with the highest stock price across all companies
highest_stock_price = np.max(stock_data)
day_with_highest_price = np.unravel_index(np.argmax(stock_data), stock_data.shape)  # Returns (row, col) index
print("\nHighest stock price across all companies:", highest_stock_price)
print("Day with the highest stock price:", day_with_highest_price[1] + 1)  # Day is index+1 (1-based)


Stock Data:
 [[150 152 155 158 160 162 165]
 [210 215 220 225 230 235 240]
 [130 132 135 137 140 145 148]
 [300 305 310 315 320 325 330]
 [ 50  52  54  55  56  58  60]]

Mean stock price for each company: [157.42857143 225.         138.14285714 315.          55.        ]

Company with the highest average stock price: Company D

Highest stock price for each company: [165 240 148 330  60]
Lowest stock price for each company: [150 210 130 300  50]

Highest stock price across all companies: 330
Day with the highest stock price: 7


In [11]:
import numpy as np
# Create a 2D NumPy array with 10 rows (competitions) and 5 columns (events)
# Each row represents a competition, and each column represents an event's score
scores = np.array([
    [85, 90, 80, 75, 88],  # Competition 1
    [78, 85, 82, 80, 91],  # Competition 2
    [92, 95, 88, 84, 90],  # Competition 3
    [80, 82, 85, 80, 86],  # Competition 4
    [90, 93, 87, 89, 92],  # Competition 5
    [95, 100, 94, 91, 98], # Competition 6
    [87, 88, 89, 85, 91],  # Competition 7
    [83, 87, 82, 79, 85],  # Competition 8
    [91, 92, 90, 88, 93],  # Competition 9
    [88, 90, 84, 83, 89]   # Competition 10
])

print("Athlete's Scores across 10 Competitions and 5 Events:\n", scores)


Athlete's Scores across 10 Competitions and 5 Events:
 [[ 85  90  80  75  88]
 [ 78  85  82  80  91]
 [ 92  95  88  84  90]
 [ 80  82  85  80  86]
 [ 90  93  87  89  92]
 [ 95 100  94  91  98]
 [ 87  88  89  85  91]
 [ 83  87  82  79  85]
 [ 91  92  90  88  93]
 [ 88  90  84  83  89]]


In [12]:
# Step 2. Calculate the average score for each event (mean across each column)
average_scores_per_event = np.mean(scores, axis=0)
print("\nAverage score for each event:", average_scores_per_event)

# Step 2. Find the event with the highest average score
event_with_highest_avg = np.argmax(average_scores_per_event)  # Index of the event with highest average
events = ["Running", "Swimming", "Cycling", "Weightlifting", "Basketball"]
print("\nEvent with the highest average score:", events[event_with_highest_avg])

# Step 2. Calculate the total score across all events for each competition (sum across each row)
total_scores_per_competition = np.sum(scores, axis=1)
print("\nTotal score for each competition:", total_scores_per_competition)

# Step 2. Find the competition with the highest total score
competition_with_highest_total_score = np.argmax(total_scores_per_competition)  # Index of the competition with highest total score
competitions = [f"Competition {i+1}" for i in range(10)]
print("\nCompetition with the highest total score:", competitions[competition_with_highest_total_score])



Average score for each event: [86.9 90.2 86.1 83.4 90.3]

Event with the highest average score: Basketball

Total score for each competition: [418 416 449 413 451 478 440 416 454 434]

Competition with the highest total score: Competition 6


In [13]:
import numpy as np

temperatures = np.array([
    [85, 87, 90, 88, 86, 85, 89],
    [78, 80, 79, 77, 81, 80, 82],
    [92, 91, 93, 94, 92, 91, 95],
    [70, 72, 68, 71, 69, 70, 73],
    [88, 85, 87, 86, 89, 90, 88],
])

mean_temps = temperatures.mean(axis=1)
print("Mean temperature per city:", mean_temps)

max_mean_index = np.argmax(mean_temps)
print(f"City {max_mean_index + 1} has the highest average temperature of {mean_temps[max_mean_index]:.2f}°.")

max_temps = temperatures.max(axis=1)
min_temps = temperatures.min(axis=1)
for i in range(temperatures.shape[0]):
    print(f"City {i + 1}: Highest = {max_temps[i]}, Lowest = {min_temps[i]}")

max_temp_value = temperatures.max()
max_temp_pos = np.unravel_index(np.argmax(temperatures), temperatures.shape)
day_with_max_temp = max_temp_pos[1] + 1
city_with_max_temp = max_temp_pos[0] + 1
print(f"The highest temperature of {max_temp_value}° occurred in City {city_with_max_temp} on Day {day_with_max_temp}.")

Mean temperature per city: [87.14285714 79.57142857 92.57142857 70.42857143 87.57142857]
City 3 has the highest average temperature of 92.57°.
City 1: Highest = 90, Lowest = 85
City 2: Highest = 82, Lowest = 77
City 3: Highest = 95, Lowest = 91
City 4: Highest = 73, Lowest = 68
City 5: Highest = 90, Lowest = 85
The highest temperature of 95° occurred in City 3 on Day 7.


In [14]:
import numpy as np

scores = np.array([
    [12, 8, 15, 10, 20],
    [14, 9, 14, 11, 22],
    [13, 7, 16, 12, 19],
    [15, 10, 13, 9, 21],
    [16, 11, 15, 14, 23],
    [14, 8, 14, 10, 20], 
    [13, 9, 15, 13, 22], 
    [15, 10, 16, 12, 24],
    [17, 12, 17, 15, 25],
    [16, 11, 14, 13, 23],
])
event_names = ['Running', 'Swimming', 'Cycling', 'Weightlifting', 'Basketball']

average_scores_per_event = scores.mean(axis=0)
for i, event in enumerate(event_names):
    print(f"Average score in {event}: {average_scores_per_event[i]:.2f}")


max_avg_index = np.argmax(average_scores_per_event)
print(f"\nEvent with the highest average score: {event_names[max_avg_index]} ({average_scores_per_event[max_avg_index]:.2f})")

total_scores_per_competition = scores.sum(axis=1)
for i, total in enumerate(total_scores_per_competition):
    print(f"Total score in Competition {i+1}: {total}")

max_total_index = np.argmax(total_scores_per_competition)
print(f"\nCompetition with the highest total score: Competition {max_total_index + 1} ({total_scores_per_competition[max_total_index]})")

Average score in Running: 14.50
Average score in Swimming: 9.50
Average score in Cycling: 14.90
Average score in Weightlifting: 11.90
Average score in Basketball: 21.90

Event with the highest average score: Basketball (21.90)
Total score in Competition 1: 65
Total score in Competition 2: 70
Total score in Competition 3: 67
Total score in Competition 4: 68
Total score in Competition 5: 79
Total score in Competition 6: 66
Total score in Competition 7: 72
Total score in Competition 8: 77
Total score in Competition 9: 86
Total score in Competition 10: 77

Competition with the highest total score: Competition 9 (86)


In [92]:
arr2 = np.arange(10,21)
print(arr2,"\n")

[10 11 12 13 14 15 16 17 18 19 20] 



In [93]:
arr3 = np.arange(111, 114)
print(arr3,"\n")

[111 112 113] 



In [94]:
combined_arr = (arr1, arr2, arr3)
print(combined_arr,"\n")

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]), array([111, 112, 113])) 



In [95]:
sliced_array1 = arr1[:-1]
print(sliced_array1,"\n")

[0 1 2 3 4 5 6 7 8] 



In [96]:
sliced_array2 = arr2[: -2]
print(sliced_array2,"\n")

[10 11 12 13 14 15 16 17 18] 



In [97]:
sliced_array3 = arr1[3 :]
print(sliced_array3,"\n")

[3 4 5 6 7 8 9] 



In [98]:
reshaped_array = arr1.reshape(2, 5)
print(reshaped_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [99]:
arr3.shape
print(arr3.shape)

(3,)


In [100]:
arr2.ndim
print(arr2.ndim)

1


In [101]:
arr1.size
print(arr1.size)

10


In [102]:
np.sqrt(arr3)
print(np.sqrt)

<ufunc 'sqrt'>


In [103]:
arr4 = np.arange(0,4,1)
print(arr4)

[0 1 2 3]


In [104]:
arr5 = np.zeros((2,2))
print(arr5)

[[0. 0.]
 [0. 0.]]


In [105]:
ones = np.ones((2, 4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [106]:
combine_array = (arr4, arr5)
print(combine_array)

(array([0, 1, 2, 3]), array([[0., 0.],
       [0., 0.]]))


In [107]:
arr = np.array([])
for arr in range(21):
    print(arr)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [ ]:
# Graded Lab Task 1

arr_2D = []

In [1]:
import numpy as np

# Creating the 2D array with stock price data for 5 companies over 7 days
stock_data = np.array([
    [150, 152, 155, 158, 160, 162, 165],  # Company A
    [210, 215, 220, 225, 230, 235, 240],  # Company B
    [130, 132, 135, 137, 140, 145, 148],  # Company C
    [300, 305, 310, 315, 320, 325, 330],  # Company D
    [50, 52, 54, 55, 56, 58, 60]          # Company E
])

# Step 1: Reshape the data if necessary
# The data is already in a 2D format of shape (5, 7), so no reshaping is needed in this case.
print("Stock Data:\n", stock_data)

# Step 2: Calculate the mean stock price for each company (mean of each row)
mean_stock_prices = np.mean(stock_data, axis=1)
print("\nMean stock price for each company:", mean_stock_prices)

# Step 3: Find the company with the highest average stock price
company_with_highest_avg_price = np.argmax(mean_stock_prices)
companies = ["Company A", "Company B", "Company C", "Company D", "Company E"]
print("\nCompany with the highest average stock price:", companies[company_with_highest_avg_price])

# Step 4: Calculate the highest and lowest stock prices for each company across all days
highest_prices = np.max(stock_data, axis=1)
lowest_prices = np.min(stock_data, axis=1)
print("\nHighest stock price for each company:", highest_prices)
print("Lowest stock price for each company:", lowest_prices)

# Step 5: Identify the day with the highest stock price across all companies
highest_stock_price = np.max(stock_data)
day_with_highest_price = np.unravel_index(np.argmax(stock_data), stock_data.shape)  # Returns (row, col) index
print("\nHighest stock price across all companies:", highest_stock_price)
print("Day with the highest stock price:", day_with_highest_price[1] + 1)  # Day is index+1 (1-based)


Stock Data:
 [[150 152 155 158 160 162 165]
 [210 215 220 225 230 235 240]
 [130 132 135 137 140 145 148]
 [300 305 310 315 320 325 330]
 [ 50  52  54  55  56  58  60]]

Mean stock price for each company: [157.42857143 225.         138.14285714 315.          55.        ]

Company with the highest average stock price: Company D

Highest stock price for each company: [165 240 148 330  60]
Lowest stock price for each company: [150 210 130 300  50]

Highest stock price across all companies: 330
Day with the highest stock price: 7


In [5]:
import numpy as np

# Creating the 2D array with stock price data for 5 companies over 7 days
stock_data = np.array([
    [156, 151, 152, 123, 143, 142, 132],  # Company A
    [225, 246, 241, 241, 243, 243, 231],  # Company B
    [125, 125, 154, 189, 196, 125, 102],  # Company C
    [364, 325, 325, 354, 335, 325, 362],  # Company D
    [525, 522, 541, 525, 545, 549, 215]          # Company E
])

# Step 1: Reshape the data if necessary
# The data is already in a 2D format of shape (5, 7), so no reshaping is needed in this case.
print("Stock Data:\n", stock_data)

# Step 2: Calculate the mean stock price for each company (mean of each row)
mean_stock_prices = np.mean(stock_data, axis=1)
print("\nMean stock price for each company:", mean_stock_prices)

# Step 3: Find the company with the highest average stock price
company_with_highest_avg_price = np.argmax(mean_stock_prices)
companies = ["Company A", "Company B", "Company C", "Company D", "Company E"]
print("\nCompany with the highest average stock price:", companies[company_with_highest_avg_price])

# Step 4: Calculate the highest and lowest stock prices for each company across all days
highest_prices = np.max(stock_data, axis=1)
lowest_prices = np.min(stock_data, axis=1)
print("\nHighest stock price for each company:", highest_prices)
print("Lowest stock price for each company:", lowest_prices)

# Step 5: Identify the day with the highest stock price across all companies
highest_stock_price = np.max(stock_data)
day_with_highest_price = np.unravel_index(np.argmax(stock_data), stock_data.shape)  # Returns (row, col) index
print("\nHighest stock price across all companies:", highest_stock_price)
print("Day with the highest stock price:", day_with_highest_price[1] + 1)  # Day is index+1 (1-based)


Stock Data:
 [[156 151 152 123 143 142 132]
 [225 246 241 241 243 243 231]
 [125 125 154 189 196 125 102]
 [364 325 325 354 335 325 362]
 [525 522 541 525 545 549 215]]

Mean stock price for each company: [142.71428571 238.57142857 145.14285714 341.42857143 488.85714286]

Company with the highest average stock price: Company E

Highest stock price for each company: [156 246 196 364 549]
Lowest stock price for each company: [123 225 102 325 215]

Highest stock price across all companies: 549
Day with the highest stock price: 6


In [6]:
import numpy as np
# Create a 2D NumPy array with 10 rows (competitions) and 5 columns (events)
# Each row represents a competition, and each column represents an event's score
scores = np.array([
    [85, 90, 80, 75, 88],  # Competition 1
    [78, 85, 82, 80, 91],  # Competition 2
    [92, 95, 88, 84, 90],  # Competition 3
    [80, 82, 85, 80, 86],  # Competition 4
    [90, 93, 87, 89, 92],  # Competition 5
    [95, 100, 94, 91, 98], # Competition 6
    [87, 88, 89, 85, 91],  # Competition 7
    [83, 87, 82, 79, 85],  # Competition 8
    [91, 92, 90, 88, 93],  # Competition 9
    [88, 90, 84, 83, 89]   # Competition 10
])

print("Athlete's Scores across 10 Competitions and 5 Events:\n", scores)

Athlete's Scores across 10 Competitions and 5 Events:
 [[ 85  90  80  75  88]
 [ 78  85  82  80  91]
 [ 92  95  88  84  90]
 [ 80  82  85  80  86]
 [ 90  93  87  89  92]
 [ 95 100  94  91  98]
 [ 87  88  89  85  91]
 [ 83  87  82  79  85]
 [ 91  92  90  88  93]
 [ 88  90  84  83  89]]


In [7]:
# Step 2. Calculate the average score for each event (mean across each column)
average_scores_per_event = np.mean(scores, axis=0)
print("\nAverage score for each event:", average_scores_per_event)

# Step 2. Find the event with the highest average score
event_with_highest_avg = np.argmax(average_scores_per_event)  # Index of the event with highest average
events = ["Running", "Swimming", "Cycling", "Weightlifting", "Basketball"]
print("\nEvent with the highest average score:", events[event_with_highest_avg])

# Step 2. Calculate the total score across all events for each competition (sum across each row)
total_scores_per_competition = np.sum(scores, axis=1)
print("\nTotal score for each competition:", total_scores_per_competition)

# Step 2. Find the competition with the highest total score
competition_with_highest_total_score = np.argmax(total_scores_per_competition)  # Index of the competition with highest total score
competitions = [f"Competition {i+1}" for i in range(10)]
print("\nCompetition with the highest total score:", competitions[competition_with_highest_total_score])


Average score for each event: [86.9 90.2 86.1 83.4 90.3]

Event with the highest average score: Basketball

Total score for each competition: [418 416 449 413 451 478 440 416 454 434]

Competition with the highest total score: Competition 6
